# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Ai(_SAP):
    _type = "ai"
    _icon_dir = "resources/sap/ai"


class BusinessEntityRecognition(_Ai):
    _icon = "business-entity-recognition.png"


class BusinessEntityRecognition_Circled(_Ai):
    _icon = "business-entity-recognition_circled.png"


class ConversationalAi(_Ai):
    _icon = "conversational-ai.png"


class ConversationalAi_Circled(_Ai):
    _icon = "conversational-ai_circled.png"


class DataAttributeRecommendation(_Ai):
    _icon = "data-attribute-recommendation.png"


class DataAttributeRecommendation_Circled(_Ai):
    _icon = "data-attribute-recommendation_circled.png"


class DocumentClassification(_Ai):
    _icon = "document-classification.png"


class DocumentClassification_Circled(_Ai):
    _icon = "document-classification_circled.png"


class DocumentInformationExtraction(_Ai):
    _icon = "document-information-extraction.png"


class DocumentInformationExtraction_Circled(_Ai):
    _icon = "document-information-extraction_circled.png"


class PersonalizedRecommendation(_Ai):
    _icon = "personalized-recommendation.png"


class PersonalizedRecommendation_Circled(_Ai):
    _icon = "personalized-recommendation_circled.png"


class SAPAiCore(_Ai):
    _icon = "sap-ai-core.png"


class SAPAiCore_Circled(_Ai):
    _icon = "sap-ai-core_circled.png"


class SAPAiLaunchpad(_Ai):
    _icon = "sap-ai-launchpad.png"


class SAPAiLaunchpad_Circled(_Ai):
    _icon = "sap-ai-launchpad_circled.png"


class SAPTranslationHub(_Ai):
    _icon = "sap-translation-hub.png"


class SAPTranslationHub_Circled(_Ai):
    _icon = "sap-translation-hub_circled.png"


class ServiceTicketIntelligence(_Ai):
    _icon = "service-ticket-intelligence.png"


class ServiceTicketIntelligence_Circled(_Ai):
    _icon = "service-ticket-intelligence_circled.png"


# Aliases
