# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Analytics(_SAP):
    _type = "analytics"
    _icon_dir = "resources/sap/analytics"


class SAPAnalyticsCloudEmbeddedEdition(_Analytics):
    _icon = "sap-analytics-cloud-embedded-edition.png"


class SAPAnalyticsCloudEmbeddedEdition_Circled(_Analytics):
    _icon = "sap-analytics-cloud-embedded-edition_circled.png"


class SAPAnalyticsCloud(_Analytics):
    _icon = "sap-analytics-cloud.png"


class SAPAnalyticsCloud_Circled(_Analytics):
    _icon = "sap-analytics-cloud_circled.png"


class SAPDataIntelligence(_Analytics):
    _icon = "sap-data-intelligence.png"


class SAPDataIntelligence_Circled(_Analytics):
    _icon = "sap-data-intelligence_circled.png"


class SAPDatasphere(_Analytics):
    _icon = "sap-datasphere.png"


class SAPDatasphere_Circled(_Analytics):
    _icon = "sap-datasphere_circled.png"


# Aliases
