# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Connectivity(_SAP):
    _type = "connectivity"
    _icon_dir = "resources/sap/connectivity"


class Bandwidth(_Connectivity):
    _icon = "bandwidth.png"


class Bandwidth_Circled(_Connectivity):
    _icon = "bandwidth_circled.png"


class ConnectivityService(_Connectivity):
    _icon = "connectivity-service.png"


class ConnectivityService_Circled(_Connectivity):
    _icon = "connectivity-service_circled.png"


class Destination(_Connectivity):
    _icon = "destination.png"


class Destination_Circled(_Connectivity):
    _icon = "destination_circled.png"


class PrivateLinkService(_Connectivity):
    _icon = "private-link-service.png"


class PrivateLinkService_Circled(_Connectivity):
    _icon = "private-link-service_circled.png"


# Aliases
