# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Lob_Industries(_SAP):
    _type = "lob_industries"
    _icon_dir = "resources/sap/lob_industries"


class SAPMarketRatesManagement(_Lob_Industries):
    _icon = "sap-market-rates-management.png"


class SAPMarketRatesManagement_Circled(_Lob_Industries):
    _icon = "sap-market-rates-management_circled.png"


class SAPOmnichannelPromotionPricing_Circled(_Lob_Industries):
    _icon = "sap-omnichannel-promotion-pricing-_circled.png"


class SAPOmnichannelPromotionPricing(_Lob_Industries):
    _icon = "sap-omnichannel-promotion-pricing.png"


class SAPVariantConfigurationAndPricing(_Lob_Industries):
    _icon = "sap-variant-configuration-and-pricing.png"


class SAPVariantConfigurationAndPricing_Circled(_Lob_Industries):
    _icon = "sap-variant-configuration-and-pricing_circled.png"


# Aliases
