# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Mobile(_SAP):
    _type = "mobile"
    _icon_dir = "resources/sap/mobile"


class Agentry(_Mobile):
    _icon = "agentry.png"


class Agentry_Circled(_Mobile):
    _icon = "agentry_circled.png"


class MobileServices(_Mobile):
    _icon = "mobile-services.png"


class MobileServices_Circled(_Mobile):
    _icon = "mobile-services_circled.png"


# Aliases
