# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Processautomation(_SAP):
    _type = "processautomation"
    _icon_dir = "resources/sap/processautomation"


class ProcessAutomation(_Processautomation):
    _icon = "process-automation.png"


class ProcessAutomation_Circled(_Processautomation):
    _icon = "process-automation_circled.png"


class SAPBuildProcessAutomation(_Processautomation):
    _icon = "sap-build-process-automation.png"


class SAPBuildProcessAutomation_Circled(_Processautomation):
    _icon = "sap-build-process-automation_circled.png"


class SAPIntelligentRpa(_Processautomation):
    _icon = "sap-intelligent-rpa.png"


class SAPIntelligentRpa_Circled(_Processautomation):
    _icon = "sap-intelligent-rpa_circled.png"


class WorkflowManagement(_Processautomation):
    _icon = "workflow-management.png"


class WorkflowManagement_Circled(_Processautomation):
    _icon = "workflow-management_circled.png"


class WorkflowService(_Processautomation):
    _icon = "workflow-service.png"


class WorkflowService_Circled(_Processautomation):
    _icon = "workflow-service_circled.png"


# Aliases
