# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _SAP


class _Runtimes(_SAP):
    _type = "runtimes"
    _icon_dir = "resources/sap/runtimes"


class AbapEnvironment(_Runtimes):
    _icon = "abap-environment.png"


class AbapEnvironment_Circled(_Runtimes):
    _icon = "abap-environment_circled.png"


class CloudFoundryRuntime(_Runtimes):
    _icon = "cloud-foundry-runtime.png"


class CloudFoundryRuntime_Circled(_Runtimes):
    _icon = "cloud-foundry-runtime_circled.png"


class Html5ApplicationRepositoryService(_Runtimes):
    _icon = "html5-application-repository-service.png"


class Html5ApplicationRepositoryService_Circled(_Runtimes):
    _icon = "html5-application-repository-service_circled.png"


class KymaRuntime(_Runtimes):
    _icon = "kyma-runtime.png"


class KymaRuntime_Circled(_Runtimes):
    _icon = "kyma-runtime_circled.png"


# Aliases
