name: Generate diagram

on:
  workflow_dispatch:

jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: Generate diagram
        run: |
          sudo apt install graphviz
          pip install graphviz          
          python tech-byte-diagram.py
          ls -ll

      - name: Upload the generated diagram
        uses: actions/upload-artifact@v4
        with:
          name: generated-diagram
          path: ./my_diagram.jpg
