name: Generate diagram

on:
  workflow_dispatch:

jobs:
  diagram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - name: Generate diagram
        run: |
          sudo apt install graphviz
          pip install graphviz          
          python tech-byte-diagram.py
          python onprem_diagram.py

      - name: Upload the generated diagram BTP
        uses: actions/upload-artifact@v4
        with:
          name: generated-diagram-btp
          path: ./my_diagram.jpg

      - name: Upload the generated diagram OnPrem
        uses: actions/upload-artifact@v4
        with:
          name: generated-diagram-onprem
          path: ./onprem_diagram.jpg
